base_rest:
    resource: "@BaseRESTBundle/Resources/config/routing.yml"
    prefix:   /

base_data_access:
    resource: "@BaseDataAccessBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
